### ISSUE TITLE
Super Hot

### ISSUE THREAD

**Issue by PlainSys** [dudenoob34/dude-zone#10]
I want it fixed, why did you have to delete the repo bro WHYYYYYYYYYYYYYYYYYYYYYY-

also im still waiting for you to add Tetris.

**Comment by dudenoob34** [comment]
perhaps

**Comment by dudenoob34** [comment]
perhaps

**Comment by dudenoob34** [comment]
perhaps

**Comment by PlainSys** [comment]
ADDD
