### ISSUE TITLE
werid fullscreen bug on floodrunner 4

### ISSUE THREAD

**Issue by dudenoob34** [dudenoob34/dude-zone#7]
so uhhh
it makes the website fullscreen but uhhh not the game fullscreen

so ye

how fix?

**Comment by dudenoob34** [comment]
hmmm
have you tried turning it on and off again-

**Comment by dudenoob34** [comment]
I TRIED TURNING IT OFF AND ON AGAIN

DO NOT DO THAT

WORST MISTAKE OF MY LIFE

**Comment by PlainSys** [comment]
My turn, I would like to nominate this award to my orthodox rabi bill clin- uhhh i mean I can try later

**Comment by PlainSys** [comment]
closed as its fixed now B)))
